# Generated by Django 2.0.1 on 2018-04-26 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import vendors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='creation datetime of the object', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='modification datetime of the object', verbose_name='modified')),
                ('title', models.CharField(help_text='title of the tag', max_length=255, verbose_name='title')),
                ('description', models.TextField(default='-', help_text='Core Details of invoice', verbose_name='Description')),
                ('invoice_code', models.CharField(default=vendors.models.gen_invoice_id, editable=False, help_text='A unique code for this invoice', max_length=16, unique=True, verbose_name='Invoice Code')),
                ('amount', models.IntegerField(help_text='amount of contract', verbose_name='Amount in Rials')),
                ('phone', models.CharField(help_text='phone number of the transferee', max_length=20, validators=[django.core.validators.RegexValidator(message='your landline phone text is incorrect , please provicde a valid number up to 15digits', regex='^\\+?\\d{9,11}$')], verbose_name='phone')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='LarinUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='creation datetime of the object', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='modification datetime of the object', verbose_name='modified')),
                ('name', models.CharField(help_text='Larin User', max_length=255, verbose_name='Larin User')),
                ('wallet_id', models.CharField(help_text='ethereum network valid id', max_length=100, validators=[django.core.validators.RegexValidator(message='wallet id should be a valid LarinToken walletID', regex='^0x[a-fA-F0-9]{40}$')], verbose_name='wallet id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LarinCustomer',
            fields=[
                ('larinuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vendors.LarinUser')),
            ],
            options={
                'verbose_name': 'Larin User',
                'verbose_name_plural': 'Larin Users',
            },
            bases=('vendors.larinuser',),
        ),
        migrations.CreateModel(
            name='LarinVendor',
            fields=[
                ('larinuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vendors.LarinUser')),
                ('full_name', models.CharField(help_text='first name of the transferee', max_length=255, verbose_name='first name')),
                ('company_name', models.CharField(help_text='Fill the title of your Company', max_length=255, verbose_name='Company Name')),
                ('company_code', models.CharField(help_text='Enter the economic code of your Company', max_length=255, verbose_name='Company Code')),
                ('national_code', models.CharField(help_text='national code of the transferee', max_length=10, validators=[django.core.validators.MaxLengthValidator(limit_value=10, message='make sure your national code is exactly 10 digits')], verbose_name='national code')),
                ('company_mail', models.EmailField(help_text='enter your Comapany Mail', max_length=254, verbose_name='Company Mail')),
                ('cell_phone', models.CharField(help_text='cell phone number of the transferee', max_length=20, validators=[django.core.validators.RegexValidator(message="phone number must be entered in the format: '+999999999'. (up to 15 digits allowed)", regex='(\\+98|0)?9\\d{9}')], verbose_name='cell phone')),
            ],
            options={
                'verbose_name': 'Larin Vendor',
                'verbose_name_plural': 'Larin Vendor',
            },
            bases=('vendors.larinuser',),
        ),
        migrations.AddField(
            model_name='invoice',
            name='owner',
            field=models.ForeignKey(help_text='owner of contract', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='vendors.LarinUser', verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='to',
            field=models.ForeignKey(help_text='Customer who needs to pay the bill', on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoices', to='vendors.LarinCustomer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor who created this invoice', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_invoices', to='vendors.LarinVendor', verbose_name='Vendor'),
        ),
    ]
