# Generated by Django 2.0.1 on 2018-04-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='larincustomer',
            name='details',
            field=models.TextField(blank=True, default='-', help_text='informations', verbose_name='Details'),
        ),
    ]
